"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Load .env from project root
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'

# Load .env from the project root
# env_path = BASE_DIR / ".env"
# load_dotenv(dotenv_path=env_path)

env_path = "/opt/csye6225/.env" if os.path.exists("/opt/csye6225/.env") else BASE_DIR / ".env"
load_dotenv(dotenv_path=env_path)

print("DEBUG: Loaded MYSQL_USER =", os.getenv("MYSQL_USER"))
print("DEBUG DB:", os.getenv("MYSQL_DATABASE"), os.getenv("MYSQL_USER"), os.getenv("MYSQL_PASSWORD"))

if os.getenv("GITHUB_ACTIONS") == "true" or "pytest" in os.getenv("PYTEST_CURRENT_TEST", ""):
    os.environ["TEST_MODE"] = "true"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a6wv$rq1g_ua3)bpsl+5+!4pwqr)tl=vpe4$0g!_n00_@ggl^j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '1.0.0.127.in-addr.arpa',]
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'api',
]

# ---------------------------------------------------------------------
# Middleware (includes logging + metrics)
# ---------------------------------------------------------------------
MIDDLEWARE = [
    "django_statsd.middleware.GraphiteRequestTimingMiddleware",
    "django_statsd.middleware.GraphiteMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "api.middleware.RequestLoggingMiddleware",
    "api.middleware.MetricsMiddleware",
    'api.middleware.RequestLoggingMiddleware',
]

ROOT_URLCONF = 'webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webapp.wsgi.application'

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("MYSQL_DATABASE"),
        'USER': os.getenv("MYSQL_USER"),
        'PASSWORD': os.getenv("MYSQL_PASSWORD"),
        'HOST': os.getenv("MYSQL_HOST", "127.0.0.1"),
        'PORT': os.getenv("MYSQL_PORT", "3306"),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# ---------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        "rest_framework.authentication.BasicAuthentication",
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# ---------------------------------------------------------------------
# Authentication and Password Validators
# ---------------------------------------------------------------------
AUTH_USER_MODEL = "api.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]

# ---------------------------------------------------------------------
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# ---------------------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------------------
import os

# Automatically ensure the directory exists (handles EC2 + CI + local)
if DEBUG:
    LOG_DIR = os.path.join(BASE_DIR, "logs")
else:
    LOG_DIR = "/var/log/webapp"

# Always attempt to create the directory (no error if it already exists)
try:
    os.makedirs(LOG_DIR, exist_ok=True)
except PermissionError:
    # In case /var/log/webapp cannot be created (e.g., permissions in CI),
    # fallback to ./logs so migrations/tests don't fail
    LOG_DIR = os.path.join(BASE_DIR, "logs")
    os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file_info': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'info.log'),
            'formatter': 'verbose',
        },
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'error.log'),
            'formatter': 'verbose',
        },
        'file_warn': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'warn.log'),
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file_info', 'file_error', 'file_warn', 'console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file_info', 'file_error', 'file_warn', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'webapp': {
            'handlers': ['file_info', 'file_error', 'file_warn', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ---------------------------------------------------------------------
# CloudWatch Metrics via StatsD
# ---------------------------------------------------------------------
INSTALLED_APPS += ['django_statsd']

STATSD_HOST = 'localhost'
STATSD_PORT = 8125
STATSD_PREFIX = 'csye6225'

S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME")
S3_BUCKET = S3_BUCKET_NAME
SNS_TOPIC_ARN = os.getenv("SNS_TOPIC_ARN")