# Generated by Django 5.2.6 on 2025-09-30 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_healthcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Quantity cannot be negative.'), django.core.validators.MaxValueValidator(100, message='Quantity cannot exceed 100.')]),
        ),
    ]
