# Generated by Django 5.2.7 on 2025-10-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='s3_bucket_path',
            new_name='s3_object_key',
        ),
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='etag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
