# Generated by Django 5.2.7 on 2025-10-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_s3_bucket_path_image_s3_object_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('product', 'file_name')},
        ),
    ]
